# Generated by Django 5.0.7 on 2024-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0003_alter_notification_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(blank=True, choices=[(1, 'follow'), (2, 'like'), (3, 'comment'), (4, 'msg')]),
        ),
    ]
