# Generated by Django 5.0.7 on 2024-08-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
