# Generated by Django 5.0.7 on 2024-08-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
