# Generated by Django 5.0.7 on 2024-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
